on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  upload:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install

      - name: Set env vars
        run: |
          echo "$STORYBLOK_TOKEN"
          echo "PUBLIC_STORYBLOK_TOKEN=$STORYBLOK_TOKEN" >> .env
          cat .env
          export $(cat .env | xargs)
          echo $PUBLIC_STORYBLOK_TOKEN
        env:
          STORYBLOK_TOKEN: test

      
      - name: Build
        run: |
          npm run build

      - name: Upload Worker Version
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name=spaceapps

